<?php

/**
 * @file
 * Change the label of Comment form button to 'Add Comment' 
 */
 
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
*/

function myAjax_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if($form_id == 'myAjax_form'){
        $form['title']['#description'] = t('This is title of document');
      }
    }

function myAjax_image_form($form, &$form_state) {
  $image_path = myAjax_get_image_path();
  // Thumbnail preview (optional).
  $form['thumbnail_preview'] = array(
    '#type' => 'item',
    '#markup' => theme('thumbnail', array(
      'path' => $image_path,
      'width' => 100,
      'height' => 100,
      'alt' => t('Example image'),
    )),
  );
 
  // Upload field.
  $form['image'] = array(
    '#type' => 'file',
    '#title' => t('Upload picture'),
    '#description' => t('Select a picture of at least @dimensionspx and maximum @filesize.', array(
      '@dimensions' => '100x100',
      '@filesize' => format_size(file_upload_max_size()),
    )),
  );
 
  // Submit button.
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save'),
  );
}

function myAjax_image_form_submit($form, &$form_state) {
  // Upload file to upload_directory in the public files dir.
  $file = file_save_upload('image', array(
    'file_validate_is_image' => array(),
    'file_validate_image_resolution' => array('500x500', '100x100'),
  ), 'public://uploaded_images/', FILE_EXISTS_RENAME);
   
  // Check if image upload was success.
  if ($file) {
    drupal_set_message(t('Image successfully uploaded.'), 'status');
  }
  else {
    form_set_error('image', t('Image was not uploaded.'));
  }
}
